[language-server.sourcekit-lsp]
command = "sourcekit-lsp"

[[language]]
name = "cpp"
file-types = ["cc", "cpp", "cxx", "hh", "hpp", "hxx", "h", "inl", "metal"]
language-servers = ["clangd", "sourcekit-lsp"]
